name: Build Docker images

on:
  push:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker
        run: docker build -t test-image:latest .